version: "3"
services:
  api:
    container_name: api
    build:
      context: ./build/api
      target: dev
    env_file: ./build/api/.env
    tty: true
    volumes:
      - .:/app
    depends_on:
      - dynamodb

  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    ports:
      - '8000:8000'
    volumes:
      - "./build/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb

networks:
  default:
    name: net
    driver: bridge
